# Generated by Django 4.2.3 on 2023-11-21 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Nombre')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.categories')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='name')),
                ('abbreviation', models.TextField(verbose_name='abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
                ('amount', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('lot_number', models.IntegerField(null=True, verbose_name='Lote')),
                ('expiration_date', models.DateField(null=True, verbose_name='Fecha de Expiración')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.elements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='elements',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.measurementunits'),
        ),
        migrations.CreateModel(
            name='Domicilies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addres', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('state', models.TextField()),
                ('total', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilie_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('domicilie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.domicilies')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.inventories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignDomicilies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domicilie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.domicilies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
