# Generated by Django 4.2.3 on 2023-11-22 02:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domicilio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domicilie_Detail',
            new_name='DomicilieDetail',
        ),
    ]
